### ISSUE TITLE
please make a example for multi-language support

### ISSUE THREAD

**Issue by lwlwlwlw** [TIBCOSoftware/spotfire-mods#10]
Hi,

Could you please make a example that illustrates how to make mod support multi-languages, i.e, label/text/description/etc automatically switch language in consistent with Spotfire Analyst/Consumer's language setting.

Thanks.

**Comment by mrylande** [comment]
Thanks for your feedback! There is currently no support for multi-languages in visualization mods. This has been logged on the TIBCO Idea portal: [.](https://ideas.tibco.com/ideas/TS-I-8086)

Regards,
Magnus
