### ISSUE TITLE
Spotfire® Mods Documentation

### ISSUE THREAD

**Issue by jleviaguirre** [TIBCOSoftware/spotfire-mods#100]
The links at the bottom of the page contains are [invalid links](https://community.tibco.com/wiki/) for both, [about ](https://tibcosoftware.github.io/spotfire-mods/about/)and [documentation ](https://tibcosoftware.github.io/spotfire-mods/docs/)pages.

Also the about page contains an [invalid link](https://community.tibco.com/wiki/tibco-labstm-spotfire-mods) to the tibco community

**Comment by objerke** [comment]
Thank you  @jleviaguirre for reporting these issues! The links have been updated.
