### ISSUE TITLE
Working with mod readers

### ISSUE THREAD

**Issue by jleviaguirre** [TIBCOSoftware/spotfire-mods#101]
The first link on the [working with readers ](https://tibcosoftware.github.io/spotfire-mods/docs/using-the-api/working-with-readables/#introduction)section contains an [invalid link](https://tibcosoftware.github.io/spotfire-mods/api-docs/interfaces/reader.html)

**Comment by objerke** [comment]
Thank you for reporting this! We have added a redirect script to the 404 page to fix incorrect casing in links.
