### ISSUE TITLE
Download of a data grid table

### ISSUE THREAD

**Issue by CommonCrisis** [TIBCOSoftware/spotfire-mods#116]
Hi,

is it possible to parse a data grid to sheetjs and download the results to excel?
For me any approach to integrate a "download button" for xslx or txt file does nothing.

**Comment by objerke** [comment]
Unfortunately it is not possible to open popups from Visualization Mods and therefore it won't be possible to download a file from within the mod. The data that a mod receives via the API can be exported via the _File > Export > Data to file_ option in the menu system, as long as the mod supports the Tooltip feature, which was added in version 1.3 of the API. [This discussion post](https://github.com/TIBCOSoftware/spotfire-mods/discussions/114#discussioncomment-5780098) explains the steps necessary to add tooltip support to an older mod. 

![image](https://github.com/TIBCOSoftware/spotfire-mods/assets/8665943/2f646cbf-c3ff-4fb3-a23a-aeea97a63d71)

![image](https://github.com/TIBCOSoftware/spotfire-mods/assets/8665943/1c49baa0-693d-436e-aeb1-b6cc7c1ae739)
