### ISSUE TITLE
Getting started link broken to example google bar chart

### ISSUE THREAD

**Issue by hski-github** [TIBCOSoftware/spotfire-mods#26]
On page https://tibcosoftware.github.io/spotfire-mods/docs/getting-started/

In the text 

> - js-dev-barchart-googlecharts This example is a basic bar chart that is built using the Google Charts library. The tutorial covers the steps taken to create this bar chart from scratch.

the link behind "tutorial" is broken. It points to 
https://tibcosoftware.github.io/spotfire-mods/tutorials/barchart-googlechart/ 

The link should point to
https://tibcosoftware.github.io/spotfire-mods/docs/tutorials/barchart-googlechart/

**Comment by dhategan** [comment]
[1b971844397a68df78980c1b216756815394f0f1] Link fixed.
