### ISSUE TITLE
Example code for marking

### ISSUE THREAD

**Issue by hski-github** [TIBCOSoftware/spotfire-mods#31]
There is some nice example code for how to implement onclick events to support marking as part of https://github.com/TIBCOSoftware/spotfire-mods/blob/master/examples/js-dev-barchart/src/main.js

But there is to my knowledge no example to implement onclick and drag and mark data in the dragged area. 

Would we great to get some example code how to implement this.

![](https://user-images.githubusercontent.com/15086293/119141626-c70d9d00-ba45-11eb-9eeb-dc3d317fed6d.png)

**Comment by objerke** [comment]
The Area chart example has drag marking implemented: https://github.com/TIBCOSoftware/spotfire-mods/blob/9b6f19b547eca483d8b3e3fc74e8292a3f81ea56/examples/js-areachart-d3/src/render.js#L284

**Comment by dhategan** [comment]
Closed issue since an answer was provided.
