### ISSUE TITLE
Create .mod for a release automatically

### ISSUE THREAD

**Issue by hski-github** [TIBCOSoftware/spotfire-mods#32]
It would be great if the .mod file could be created via command line like using npm command. Maybe there is also a way to utilize Github Actions to automatically create not only a zip of the source code when creating a release in Github. This would simplify process of creating a new release.

**Comment by objerke** [comment]
It is possible to package and sign mods directly via the [TIBCO Spotfire Package Builder](https://docs.tibco.com/pub/sfire_dev/area/doc/html/devdoc/topics/signing_a_visualization_mod_using_package_builder.html). The package builder is not available via any package manager.

It can be downloaded directly from the [downloads](https://spotfire-next.cloud.tibco.com/spotfire/wp/startPage#/downloads) section at TIBCO Spotfire Cloud, or via via eDelivery as part of [TIBCO Spotfire Developer software](https://docs.tibco.com/pub/sfire_dev/area/doc/html/devdoc/topics/downloading_tibco_spotfire_developer.html).
 
I'm unsure about the possibilities of GitHub actions, but package builder is a Windows tool which can be executed with command line parameters, so it is possible to automate the tool.

**Comment by hski-github** [comment]
I am working with Mac and TIBCO Spotfire Business Author. Therefor a possibility to create mod packages via npm or non-Windows would be appreciated.

**Comment by hski-github** [comment]
Or get the possibility to download a mod from the Spotfire library to share with others. 
![image](https://user-images.githubusercontent.com/1921015/120241615-69f2c200-c263-11eb-9e5f-296730983272.png)

**Comment by mrylande** [comment]
Added two ideas on TIBCO Idea portal:

- https://ideas.tibco.com/ideas/TS-I-8309
- https://ideas.tibco.com/ideas/TS-I-8308

**Comment by hski-github** [comment]
Thank you!
