### ISSUE TITLE
How to update to mods 1.1

### ISSUE THREAD

**Issue by hski-github** [TIBCOSoftware/spotfire-mods#33]
Would be great if the documentation in the FAQ would contain information how to update to mods 1.1

Is it as simple as changing "apiVersion": "1.0" to  "apiVersion": "1.1"?

But autocompletion in Eclipse (similar to Intellisense in Microsoft VS) does not show the new attributes of 1.1 e.g. DataViewRow row.elementId.

Any idea?

**Comment by hski-github** [comment]
Guess I have to update spotfire/mod-schema.json and spotfire/spotfire-api.d.ts

**Comment by objerke** [comment]
I've added a section on in the readme on how to update a mod to a newer version. https://github.com/TIBCOSoftware/spotfire-mods#updating-an-existing-mod-project-to-a-newer-api-version
