### ISSUE TITLE
Please provide code examples of the manifest entries

### ISSUE THREAD

**Issue by jplerxt** [TIBCOSoftware/spotfire-mods#39]
Hi,

I am trying to get a Spotfire document property into my new mod, and am finding that it "doesn't exist" at run time. I am rying to figure out the steps involved in exposing it to the mod, and having a problem. I have the property in the document, I add it into the  render function etc., in the code, and think it needs to also be accounted for in the manifest. Cannot figure out the magic needed to account for it in all needed places. Having examples of "how to add a Spotfire document property" would be immensely helpful.

**Comment by objerke** [comment]
Spotfire `document properties` are not part of a mod's manifest. Instead they are part of a document/analysis file. A mod can read and modify existing `document properties` but it cannot create new ones. If a mod has a dependency on a particular `document property`, it has to be added manually to the document.

To read all available document properties you can do the following 
```
mod.createReader(mod.document.properties()).subscribe(properties => {
    console.log("all available properties in the document", properties);
});
```

You can also do something like this to notify the user that the mod requires a certain document property 
```
mod.createReader(mod.document.property("myProperty")).subscribe(myProperty => {
    console.log(myProperty)
}, () => {
    mod.controls.errorOverlay.show("Document property `myProperty needs to exist for this mod to function`")
})
```

A `mod property` on the other hand is defined in the mod manifest and is the way to store any local state in the Mod. Most examples use [mod properties](https://github.com/TIBCOSoftware/spotfire-mods/blob/99d00d9d155953e63ab61077c77177b0216f6e46/examples/js-areachart-d3/static/mod-manifest.json#L7) in some form and they can be used as examples.

**Comment by hski-github** [comment]
Great explanation and background information. Worth to put on the documentation wiki.
