### ISSUE TITLE
React example

### ISSUE THREAD

**Issue by adiamaan92** [TIBCOSoftware/spotfire-mods#45]
I have been trying to integrate React into Spotfire Mods since I know it is possible as shown in this youtube video,
https://www.youtube.com/watch?v=gexpop2grIM&t=2374s.

Can we get the DR-SPOTFIRE-MODS-REACT-DEMO repo included in the spotfire-mod examples repo, so that it is easier to get started?

![Capture](https://user-images.githubusercontent.com/8073406/133127922-cf8b40ff-a11e-4960-ae6c-5c0f9beb0d8f.PNG)

**Comment by objerke** [comment]
Hi @adiamaan92! Thank you reaching out. I've added the Dr Spotfire example to the [prototypes](https://github.com/TIBCOSoftware/spotfire-mods/tree/master/prototypes) folder here: 

https://github.com/TIBCOSoftware/spotfire-mods/tree/master/prototypes/dr-spotfire-mods-react-demo-property

Please keep in mind that this prototype has not been tested and was created to exemplify the wide range of libraries that can be used with Spotfire mods. I still hope it can be useful.
