### ISSUE TITLE
Tutorial and examples info

### ISSUE THREAD

**Issue by ayh20** [TIBCOSoftware/spotfire-mods#5]
As we are suggesting that people use VS Studio as the editor it would be a good idea to show them how to install necessary typescript files for the editor.

For example on the tutorial the google visualization types are at:

npm install @types/google.visualization

**Comment by mhooi** [comment]
I was wondering if the .Mod files are also available somewhere? So we can directly import the new files into Spotfire

**Comment by objerke** [comment]
@ayh20 The `js-dev-barchart-googlecharts` example has been updated with types.

@mhooi packaged .mod files are currently not available. Some mods will be available on [TIBCO® Exchange](https://community.tibco.com/exchange) in the future.
