### ISSUE TITLE
Leaflet.js map error - content security policy violation

### ISSUE THREAD

**Issue by kivvok** [TIBCOSoftware/spotfire-mods#57]
Hi!

I am trying to use a leaflet.js map in the mods with Tibco map tile from https://geoanalytics.tibco.com/tile/rich_ref_map_dark/{z}/{x}/{y}.png.
![image](https://user-images.githubusercontent.com/97734508/149505222-56acff1b-1f56-488f-86df-80ca916b7244.png)

Everything works fine while using the development server, but whenever i disconnect to embed the visualization mod in the analysis a Content Security Policy error message comes up in the console and it refuses to load the tile images of the map. 
![image](https://user-images.githubusercontent.com/97734508/149505145-0b6f184f-b2a9-4dab-ac9f-8485db99c514.png)
![image](https://user-images.githubusercontent.com/97734508/149505308-120a46af-691f-44fd-beb4-5da26769fe6c.png)
I have tried to enable all content in the meta tag of the index.html head, but the error msg still occurs when disconnecting:
![image](https://user-images.githubusercontent.com/97734508/149505546-555bf6df-e987-4351-8d74-f54213e2e2ad.png)
I would appreciate any idea on this problem.
Thanks,
V

**Comment by ebrandin** [comment]
Hi @kivvok,

For security reasons all external resources must be declared in the mod manifest. Try adding this section to you mod-manifest.json file:
`    "externalResources": ["https://geoanalytics.tibco.com"]
`

**Comment by kivvok** [comment]
Hi @ebrandin ,
Thank you very much! This has solved my problem. :)
