### ISSUE TITLE
How to export a mod visualization to image (png) with IronPython

### ISSUE THREAD

**Issue by mwdpb** [TIBCOSoftware/spotfire-mods#58]
Hi, I have a custom mod visualization that I'd like to export to png file with IronPython script.  The script below works for a native Spotfire vis, but it failed on a mod vis.  I then tried  Spotfire native export button (File->Export->Visualization to image...) and it works just fine.  So I believe it is achievable, can anyone help me on what API function I should use to accomplish this goal?  Thank you!

```
from System.Drawing import Bitmap, Graphics, Rectangle, Point
from System.Drawing.Imaging import ImageFormat

for v in Document.ActivePageReference.Visuals:
	w, h = 100, 100
	bm = Bitmap(w, h)
	g = Graphics.FromImage(bm)
	g.TextRenderingHint = g.TextRenderingHint.AntiAlias
	_ = v.Render(g, Rectangle(Point(0, 0), bm.Size))
	fname = "G:\\test.jpg"
	bm.Save(fname, ImageFormat.Png)
```

**Comment by objerke** [comment]
Hi @mwdpb, You should use the newer [`Visual.RenderAsync`](https://docs.tibco.com/pub/doc_remote/sfire_dev/area/doc/api/TIB_sfire-analyst_api/Index.aspx?topic=html/T_Spotfire_Dxp_Application_Extension_CustomVisualView.htm) method to render mods. The [`Visual.Render`](https://docs.tibco.com/pub/doc_remote/sfire_dev/area/doc/api/TIB_sfire-analyst_api/Index.aspx?topic=html/T_Spotfire_Dxp_Application_Extension_CustomVisualView.htm) method is classified as obsolete.

The following code snippet is taken from [this example](https://community.tibco.com/wiki/using-visualrendersync-api-export-visualization-current-theme-using-ironpython-scripting-tibco) and it works for mods.
```python
from Spotfire.Dxp.Application.Visuals import *
from System.Drawing import Size
from System.Threading import CancellationToken 
from Spotfire.Dxp.Application.Visuals import RenderResultSettings

viz = Document.ActivePageReference.ActiveVisualReference
s=Size(1000,500)
rrs=RenderResultSettings(s)
vrs=VisualRenderSettings()
ct=CancellationToken()

renderResult=viz.RenderAsync(rrs,vrs,ct)
img=renderResult.Result.AsImage()
img.Save("C://temp//viz.png")
```

For more information about the Export APIs you can read [this article](https://community.tibco.com/wiki/tibco-spotfirer-712-apis-exporting-and-rendering-visualizations#toc-10).

**Comment by mwdpb** [comment]
Hi @objerke, thanks for the quick reply.  I tried your code and result in the following error, any idea why?  

![image](https://user-images.githubusercontent.com/55845355/151208262-da820ccf-7193-4dd0-8675-5dc803c86f12.png)

**Comment by objerke** [comment]
Yes, you are not allowed to run the script in a transaction. There is a checkbox in the dialog screenshot that should not be checked. It is also mentioned in the linked example.

**Comment by mwdpb** [comment]
Got it, thank you very much!
