### ISSUE TITLE
Trusting certificate

### ISSUE THREAD

**Issue by Justformoment** [TIBCOSoftware/spotfire-mods#59]
Hi team,

I'm not sure, if this is a place to ask such kind of question, anyway, someone may guide me how to solve my issue. The issue is that we have tested one of mods(barcharts in examples folder), the thing is that it keeps asking to trust TIBCO certificate in Web Client and SF Analyst. What we tried to do is that, we signed the mod using our internal code signing certificate, but it still asks you to trust it ONLY once. This scenario would work for us, but it's not ideal for end users... Here is the question: How we can sign a mod in a way it wouldn't prompt for trusting it?
Thank you in advance!

**Comment by ebrandin** [comment]
Hi

The certificate needs to be trusted for a group that the user belongs to.

More details can be found here:
https://docs.tibco.com/pub/spotfire_server/latest/doc/html/TIB_sfire_server_tsas_admin_help/server/topics/trusting_custom_content_in_the_spotfire_environment.html

or more specifically:
https://docs.tibco.com/pub/spotfire_server/latest/doc/html/TIB_sfire_server_tsas_admin_help/server/topics/adding_trusted_signers_to_a_group.html
