### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by rajeshnai** [TIBCOSoftware/spotfire-mods#6]
Hi Team,

The document doesn't have the process/steps to enable the Mods in the Spotfire analyst.
Please add that also in documentation.

**Comment by mrylande** [comment]
Hi,
Thanks for your feedback on Mods. With "process/steps to enable the Mods in the Spotfire analyst" do you refer to how to add and use a mod in Spotfire Analyst or how to configure the licenses to enable the feature or something else?

**Comment by objerke** [comment]
This GitHub repo is mainly used for examples and documentation of the Mods API. For additional product documentation of Spotfire Mods you can look at the following resources:
- [Web client documenation](https://docs.spotfire.cloud.tibco.com/spotfire/GUID-6A2910C6-A44D-48B5-B80A-1D959DA3E63C.html)
- [Analyst client documentation](https://docs.tibco.com/pub/sfire-analyst/11.1.0/doc/html/en-US/TIB_sfire-analyst_UsersGuide/index.htm#t=modvis%2Fmodvis_how_to_use_a_visualization_mod.htm&rhsearch=mods&rhhlterm=mods&rhsyns=%20)
- [Administration Manager – User's Manual](https://docs.tibco.com/products/tibco-spotfire-analyst-11-1-0) which contains information about preferences and licenses regarding mods.
