### ISSUE TITLE
Best way to check if axis has been configured

### ISSUE THREAD

**Issue by hski-github** [TIBCOSoftware/spotfire-mods#62]
What is the best and secure way to check if an axis was defined by the user of the mod e.g. Axis.expression is not null? 
https://tibcosoftware.github.io/spotfire-mods/api-docs/interfaces/axis.html#expression

**Comment by objerke** [comment]
I would say that the best to see if an axis is empty is to check if the parts array is empty, e.g.  `axis.parts.length == 0`.

**Comment by hski-github** [comment]
Works nice. Thank you!
