### ISSUE TITLE
How to cast a mod visual to its concrete type in C# API?

### ISSUE THREAD

**Issue by mwdpb** [TIBCOSoftware/spotfire-mods#65]
For a native vis, for example, ScatterPlot, we can do the following cast in C# to get its specific properties.

``` 
Visual vis = page.ActiveVisualReference;
ScatterPlot scatterPlot = vis.As<ScatterPlot>();
```

How can we do the similar casting for a mod vis in order to get its properties such as its "Legend" and "ColorAxis"?

**Comment by mwdpb** [comment]
FWIW, in IronPython, the following statement runs OK:

```
print(visual.As[VisualContent]().Legend.Width)
```

However, the `VisualContent` in C# API doesn't have `Legend` property and therefore you can't get it compiled, see image below:

![image](https://user-images.githubusercontent.com/55845355/154502685-6a9f1118-7faa-433e-be65-fc1cd471db38.png)

**Comment by objerke** [comment]
That is currently not available as those Mod specific features are not covered by any public API. Please file an idea in the [Ideas portal](https://ideas.tibco.com/ideas?category=6928343615694750134) for future consideration.
