### ISSUE TITLE
How can I check if an axis is aggregated or not?

### ISSUE THREAD

**Issue by lwlwlwlw** [TIBCOSoftware/spotfire-mods#67]
How can I check if an axis is aggregated or not? Thanks.

**Comment by objerke** [comment]
Could you explain what use case you are trying to solve? [Mod data views are always aggregated](https://tibcosoftware.github.io/spotfire-mods/docs/using-the-api/mod-data-views/#using-non-aggregating-expressions-on-a-continuous-axes). The `allowNonAggregatingMeasures` option for axes in the mod manifest allows a measure to be split into its unique values, but it will collapse duplicates.

**Comment by lwlwlwlw** [comment]
The use case is to draw a contour chart, with X and Y are passed from Spotfire and all data should be reserved as is, rather than aggregated. I need to check if axis is aggregated and show warnings if it is.

Thanks.

**Comment by objerke** [comment]
Hi @lwlwlwlw, Please use a single place for asking questions regarding mods. I have provided a potential way forward in the  [TIBOCO Idea portal question](https://ideas.tibco.com/ideas/TS-I-8685). We prefer issues regarding the documentation and the existing mods in this Issue tracker.
