### ISSUE TITLE
How do I change the default port number of 8090?

### ISSUE THREAD

**Issue by mwdpb** [TIBCOSoftware/spotfire-mods#68]
I'm simultaneously developing 3 mods and would like to have them on different ports instead of the default port of 8090.  I searched all the configuration files and seems that the port number is no where to be found.  Please advice, thank you!

**Comment by objerke** [comment]
Version 1.0.1 of the mods-development-server was recently released on npm and it adds support for configuring the server port. Update to the latest version by calling `npm install @tibco/spotfire-mods-dev-server`, and then use the new --port configuration flag. 
```
mods-dev-server --port 8091 --open false src 
```

The documentation is intended to mention the new configuration when all code examples use the newer package version.

**Comment by objerke** [comment]
The configuration is now listed here: https://github.com/TIBCOSoftware/spotfire-mods/tree/master/tools/mods-dev-server#configuration

**Comment by mwdpb** [comment]
Thanks, that worked!
