### ISSUE TITLE
Issue with Progress on Gantt Chart 

### ISSUE THREAD

**Issue by lubel2** [TIBCOSoftware/spotfire-mods#76]
Hello, I used the Gantt Chart from the Mod Visualization. But I have a little issue. I have 2 task level. I can display the right progress for Task lvl 2 but numbers are wrong for the Task lvl 1. 

Can someone help me on that please ?

**Comment by objerke** [comment]
Hi @lubel2, Please take a look a the Data requirement section in the documentation at the [TIBCO Community](https://community.tibco.com/modules/gantt-chart-mod-tibco-spotfirer?qt-module_detail_tabs=3#qt-module_detail_tabs) and see if your configuration matches the one described there.
