### ISSUE TITLE
Does Mod Support Trellis Axis?

### ISSUE THREAD

**Issue by mwdpb** [TIBCOSoftware/spotfire-mods#77]
Mods support native color axis, does it support trellis axis?

**Comment by objerke** [comment]
The mods framework does not currently support the native Spotfire trellis functionality. Something similar can be implemented within the mod by adding an additional axis to the mod manifest.

**Comment by hski-github** [comment]
You can name the axis Trellis and can give it even a dropTarget icon for Trellis. 😊 https://tibcosoftware.github.io/spotfire-mods/docs/using-the-api/mod-schema/

**Comment by jleviaguirre** [comment]
Is there any example or current Mod that does trellising?
