### ISSUE TITLE
Banned outdated libraries in version 1.2

### ISSUE THREAD

**Issue by heberleh** [TIBCOSoftware/spotfire-mods#82]
At Bayer we use a specific long term version of Spotfire, which doesn't allow us to try the most up to date mod examples.

Could you please upgrade the versions of libraries of Mods API version 1.2?

For some reason, one of the versions of the sub-dependencies is banned. 
Upgrading the libraries worked, but then the example was broken.

The problem occurs when trying to run `npm install` with outdated libs (probably with high security risk).

The package-lock was also created with an old node version.

**Comment by heberleh** [comment]
Turned out to be another problem with npm and authentication.

However, some libraries with critical security risks are still there and npm audit fix won't fix automatically.

**Comment by objerke** [comment]
We have updated all dependencies in release [1.2.1](https://github.com/TIBCOSoftware/spotfire-mods/releases/tag/1.2.1). It should now be compatible with the latest Node LTS version.
