### ISSUE TITLE
ColorAxes?

### ISSUE THREAD

**Issue by heberleh** [TIBCOSoftware/spotfire-mods#84]
How can we have multiple ColorAxes defined in the mod-manifest.json?

I'm using the LTS version 
TIBCO® Spotfire® 11.4.1 LTS

**Comment by objerke** [comment]
Hi @heberleh. This is currently not possible in the Mods API. The [mod-manifest schema](https://tibcosoftware.github.io/spotfire-mods/docs/using-the-api/mod-schema/) specifies the `colorAxis` as a single Axis. There is an idea for multiple color axes in the Idea portal. Please vote for it [here](https://ideas.tibco.com/ideas/TS-I-8051).
